# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jonie & Ritie
subtitle: 'Jonas & Rita '' Neverland'
description: 'Arts of love & persistence'
keywords: ["Jiannan Lu","Jiayi Zhu","Jonas","Rita","Jonie","Ritie","Jonas Lu","Rita Zhu"]
author: Jonas & Rita
language: en
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://www.ritie-jonie.space
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - "*"
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cupertino

# add waline comment
# please trans to post.js to change
waline:
  serverURL: "'https://comment.ritie-jonie.space/'"
  path: window.location.pathname.replace(/\/$/,'')
  copyright: false
  dark: "'body[data-current-color-scheme=\"dark\"]'"
  comment: true
  requiredMeta: "['nick','mail']"
  login: "'disable'"
  emoji: "['https://unpkg.com/@waline/emojis@1.0.1/bilibili','https://unpkg.com/@waline/emojis@1.0.1/qq','https://unpkg.com/@waline/emojis@1.0.1/weibo','https://unpkg.com/@waline/emojis@1.0.1/tieba']"

# add 'trigger of css transform while scrolling'
scrollreveal: true

busuanzi:
  enable: true

# generate data required for wechat miniprogram
restful_api:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true         # 分类数据
  use_category_slug: false # Use slug for filename of category data
  tags: true               # 标签数据
  use_tag_slug: false      # Use slug for filename of tag data
  post: true               # 文章数据
  pages: false            # 额外的 Hexo 页面数据, 如 About
  swipers_list: [summary-2022summer,ceremony-1year,summary-2022spring,ceremony-300days,summary-2021winter]          # 生成指定的页面信息,做指定的轮播文章展示
  search_all:                  #  配置全局搜索
    enable: true
    path: api/search.json
    field: post
    content: true

# Deployment
# Deploy时，命令行输入
# git config --global http.proxy http://127.0.0.1:7890
# git config --global https.proxy http://127.0.0.1:7890
# 再使用 hexo clean && hexo deploy 部署到 github 服务器（pull request会被vercel服务器自动接管）
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/jonie-ritie/jonie-ritie.github.io.git
  branch: main